###
GRAPHQL http://localhost:8082/mygraphql

mutation  addPerson1 {
    addPerson1 {
        id
        firstname
        lastname
    }
}

###
GRAPHQL http://localhost:8082/mygraphql

query  {
  allPersonQuery {
    id
  }
}

###
GRAPHQL http://localhost:8082/mygraphql

query  {
    personByNames {
        id
        firstname
        lastname
        id
    }
}
